baseURL = "http://www.hinter-dem-mond.de/"
languageCode = "de-de"
title = "Hinter dem Mond"
theme = "dream"
defaultContentLanguage = "de"

[params]
    showSummaryCoverInPost = true
    rss = true
    email = "social@hinter-dem-mond.de"
    facebook = "hinterdemmond"
    instagram = "hinter_dem_mond_shop"
